region = "us-east-2"
environment = "dev"
tf_state_vpc_bucket_name = "aws-us-east-2-dev-vpc-tf-state-bucket"
tf_state_vpc_key_name = "env:/dev/vpc-dev.tfstate"
tf_state_gateways_bucket_name = "aws-us-east-2-dev-gateways-tf-state-bucket"
tf_state_gateways_key_name = "env:/dev/gateways-dev.tfstate"