AWSTemplateFormatVersion: '2010-09-09'
Description: Secret resources

Parameters:
  
  SecretName:
    Default: ''
    Description: Friendly name of the secret
    Type: String

Resources:

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: 'This is the secret for the RDS instance'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "rdssecretuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

Outputs:

  RDSSecretName:
    Description: Name of secret in Secret Manager.
    Value: !Ref SecretsManagerSecret