region = "us-east-2"
environment = "dev"
tf_state_vpc_bucket_name = "aws-us-east-2-dev-vpc-tf-state-bucket"
tf_state_vpc_key_name = "env:/dev/vpc-dev.tfstate"
tf_state_security_groups_bucket_name = "aws-us-east-2-dev-security-groups-tf-state-bucket"
tf_state_security_groups_key_name= "env:/dev/security-groups-dev.tfstate"
keypair_name = "aws-us-east-2-dev-jenkins-keypair"