region = "us-east-2"
environment = "qa"
tf_state_vpc_bucket_name = "aws-us-east-2-qa-vpc-tf-state-bucket"
tf_state_vpc_key_name = "env:/qa/vpc-qa.tfstate"
tf_state_gateways_bucket_name = "aws-us-east-2-qa-gateways-tf-state-bucket"
tf_state_gateways_key_name = "env:/qa/gateways-qa.tfstate"