region = "us-west-1"
environment = "dev"
application_name = "terraform-demo"
beanstalk_service_role_name = "us-west-1-dev-beanstalk-service-role"
beanstalk_ec2_instance_profile_name = "us-west-1-dev-beanstalk-ec2-instance-profile"
beanstalk_ec2_instance_role_name = "us-west-1-dev-beanstalk-ec2-instance-role"